    name: Generate KiCad Outputs

    on:
      push:
        branches:
          - main # Trigger on pushes to the main branch

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Generate KiCad outputs
            uses: obra/kicad-exports@v1 # Use the kicad-exports action
            with:
              project-path: './schematic' # Path to your KiCad project
              output-path: './' # Directory to save generated files
              outputs: 'schematic_pdf'